FROM ubuntu:latest
RUN apt-get update -y \
  && apt-get install -y python3-pip python3-dev postgresql postgresql-contrib \
  && apt-get install -y python-psycopg2 \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
CMD ["flask", "run"]